all: dynamic

LIBRARIES = -lbam -lm -lz -lpthread
LIBRARIESDIR = ./lib/linux64/
INCLUDESDIR = ./include/
CC = gcc
CFLAGS = -g -w -Wall -O2 -std=c11
APPNAME = pacbam

dynamic: 
	$(CC) $(CFLAGS) -I$(INCLUDESDIR) pacbam.c -o $(APPNAME) -L$(LIBRARIESDIR) $(LIBRARIES) 
	
static: 
	$(CC) $(CFLAGS) -I$(INCLUDESDIR) pacbam.c -o $(APPNAME) -L$(LIBRARIESDIR) $(LIBRARIES) -static
	
clean: 
	rm -f *.o 
